### PR TITLE
Provide a table of contents for the spec report

### PR DESCRIPTION
**Pull request by Slugger**
Typically I need to scroll down to the failures; providing a TOC makes
that a breeze.

### CODE REVIEW

**Comment by rdmueller** [comment]
That might be a good idea, but I would prefere to solve this though a report template. Groovy provides support for templates:
http://groovy.codehaus.org/Groovy+Templates

**Comment by Slugger** [comment]
If the ultimate goal is to replace the existing MarkupBuilder with templates then that makes sense, but building a TOC from a template while the rest of the page is built via the builder seems more confusing to me.

This patch at least provides a sol'n that is in line with the current implementation.  Moving the TOC to a template could be done in step with converting the rest of the reports.

**Comment by rdmueller** [comment]
yes, I do agree - it does not make much sence to only provide the TOC as template. But I would be happy if someone could come up with a second report generator which is capable of using template :-)

**Comment by Slugger** [comment]
Changes to the html cause the one test in HtmlReportCreatorSpec to fail.  Unmodified, the test case failure actually causes an OOM exception as spock tries to report the string diff and dies trying.  I've spent a good chunk of my evening trying to get the expected html to match up and just can't quite get it right.  Any secret?  Is there actual value to this particular test case?

**Comment by renatoathaydes** [comment]
When I designed the report creator, I started with the html (and the test) and made the implementation work later. So the test is very valuable in the sense that it dictates what the report should look like, not the code.

I like your initiative to do this, but I believe you should have first made a feature proposal. This plugin is used by many thousands of projects and if we're going to change the report looks, we should consult with the users first.

Do you mind if I ask you to create a feature request for this? And hopefully we can get some votes for and against it? Can you create a codePen showing what the report will look like also?

Finally, I can definitely create a template mechanism for spock-reports. Please make a feature request as well!

**Comment by Slugger** [comment]
I'll look into creating a CodePen, etc. at some point.  Basically, what I'm doing is halting my efforts to roll my own report generator for another project and replacing it with this + some enhancements.  Not sure how much time I'll have to do up proposals & mocks of the UI changes, etc.  Instead I'll just keep pushing enhancements that I think might be beneficial upstream and if you disagree just close them.  I now realize mods to the report markup are not ideal so I won't bother pushing any of those. :)  Either way I was going to have to build and publish my own version because I'll be making some mods in the next week or so that are very specific to my use case and I know you won't need/want them merged back to your master.

**Comment by Slugger** [comment]
Actually seems the unit tests run the FakeTest template thru so here's a codepen of what that looks like with this enhancement:

http://codepen.io/anon/pen/emEJVN

What I changed:

* TOC created under `Features:` heading
* TOC items are colour coded by pass (green), fail (red) or skipped (grey)
* Each feature header includes a return link back to the TOC, floated to the right
* Supporting CSS changes

**Comment by renatoathaydes** [comment]
Wow, I like the ToC! Just minor comment: my convention is that failures are Red, errors are Orange... but anyway, I will check the code a bit more soon and merge this when possible. I think I will also add a config option to disable ToC...

Thank your for your contributions! It's been really good to get some help with this!

**Comment by renatoathaydes** [comment]
Hi @Slugger I have been really busy with other project, but now finally I had some time to check this out. Got 2 tests failing in this PR.

* `A correct HTML report is generated for a spec including different types of features`
* The settings found in the config.properties file are read only once

I will try to fix them myself, but please make sure to run all tests when you make a PR.

**Comment by renatoathaydes** [comment]
Ah, the first test was failing because I ran with Java 8 and that seems to have broken a Groovy mock... nothing to worry... the other one is as expected... we need to update what the expected report looks like.

**Comment by Slugger** [comment]
Yeah, I tried to fix the expected report but couldn't get it just right.  As mentioned above, when that test fails for me it actually causes the JVM to run out of memory, making it even harder (groovy's power assert calculator runs out of memory trying to find the diffs between the huge strings).  Do you have any tricks to update the expected result for that test?

**Comment by renatoathaydes** [comment]
It never runs out of memory for me. No tricks.... I can even see the difference quite well in IntelliJ. I am almost done updating the tests... will push to this PR (if I can).

**Pull request closed without merging**
