### PR TITLE
Next release (1.2.14)

### PR DESCRIPTION
**Pull request by renatoathaydes**

### CODE REVIEW

**Comment by renatoathaydes** [comment]
@hexmind @rdmueller you guys are participating in this release, thanks for that! Just one small favour, before we can release version 1.3.0 (bumped the minor version as there's a lot in this release)... can you checkout `next` and make sure it is all working for you, including the vivid report feature for MD and HTML?

If you guys can confirm that, I will push the button!

**Comment by rdmueller** [comment]
ok. give me some time...

**Comment by hexmind** [comment]
Ok, I have been tested MD and HTML on 20 real features.
And HTML on spock-reports recursive.

**Comment by rdmueller** [comment]
OK, I have tested:

- the build on windows: OK
- my standard test-suite with template reports, geb and screenshots. Results are the same. Debug `println` statements where output in the old version to `build\test-results\TEST-BasicTestsSpec.xml` and are missing in the new version, but that's ok.

**Comment by rdmueller** [comment]
in addition, I have now tested:
* my standard test suite with vivid reports (asciidoc template)

works like a charm!

Great Feature!!!

**Comment by renatoathaydes** [comment]
That's really great, thanks both @rdmueller and @hexmind! I will release tonight (unless something happens)!

**Comment by rdmueller** [comment]
@renatoathaydes @hexmind : thanx to both of you, I could brush up my asciidoc test report!

http://rdmueller.github.io/etka15/report/docs/html5/summary.html

**Pull request merged**
