### PR TITLE
Produce full stacktraces for problem reports

### PR DESCRIPTION
**Pull request by Slugger**
When a test fails, full stacktraces are better than getMessage()

Also removed the call to format the string to html; shouldn't be
necessary inside a `<pre>` and calling it ruins the formatting of the
stacktrace.

My plan is to submit any features I think you might want to merge into master as PRs; if it's not a feature you want just close the PR and I'll just leave it in my fork.

### CODE REVIEW

**Comment by rdmueller** [comment]
Sound like a good feature to me....

**Comment by Slugger** [comment]
See comment in #27 about OOM error with unit test.  Same thing happens here.

**Comment by renatoathaydes** [comment]
I decided to release 1.2.4 without this feature... I am not sure the report is the best place to analyse a stack-trace... isn't the stack trace already printed during the execution of the test, usually? Anyway, if we really think the stack trace should be shown in the report, I guess the default should be for it to be hidden, requiring users to click on a + button to open it up... @Slugger would you be willing to try to do that?

By the way, I have released 1.2.4 with all your contributions! Thanks a lot!

**Comment by Slugger** [comment]
It'll be a couple of weeks probably before I can, but I will take a look at it.

**Comment by Slugger** [comment]
I've updated this PR with the "full trace hidden by default" functionality.  Please have a look at commit af3052.  The commit message is rather descriptive about what's going on; this is an initial attempt that still needs some work, but want to make sure we're all on the same page before investing much more time on it.

Awaiting feedback.

**Comment by Slugger** [comment]
New branch off of next created to replace this

**Pull request closed without merging**
