### PR TITLE
Fix (#235) VividAstInspector not accounting for indents 

### PR DESCRIPTION
**Pull request by Gleethos**
I fixed the bug described in #235, however
there were 2 places where I had to adjust the specifications in the test suite
because the expected results were also missing indents.
I hope these changes are fine, nothing is broken and I already tested
these changes on 1400+ tests, the reports were all generated well.

I also added a new test which ensures that indents are preserved.

### CODE REVIEW

**Comment by renatoathaydes** [comment]
Hi @Gleethos  and thanks for your pull request.

I had a look at your changes, and even though I see you spent some effort to fix the problem, which I appreciate a lot, I would like to propose a simpler set of changes that I believe is sufficient to fix the problem described in #235.

Could you please check it out? If you could try running your tests with the `dev` branch to confirm those changes work, that would be very helpful so I can release the fix as soon as possible.

My reasons for preferring my own smaller changeset are:

* this PR contains code copied from the Spock project. I prefer to avoid doing that for many reasons, but mostly so that Spock changes in the future don't break spock-reports.
* the changes were quite a lot broader than necessary. I tend to be very cautious changing anything because a lot of people rely on this project and I don't want to break things for them.
* the new test was unnecessary as adapting existing tests is enough to cover the fix. Having more tests than necessary is undesirable as test times should remain as short as possible.

**Comment by Gleethos** [comment]
Thank you for addressing this so quickly!

I had hoped my understanding of the code was sufficient for this change so that you wouldn't have to invest so much time. Thank you for working on this!

Sorry I have not yet had the time to check out your changes and validate them with my test suites.
I will run the changes as soo as I get back to my workstation.

**Comment by renatoathaydes** [comment]
One thing I didn't realize was that you seem to have addressed issue #237 in this pull request. I was not looking into that as it was never mentioned in this PR! Now I understand why I had thought you made too many changes to fix only #235.

I do want your changes to fix #237 though... so can you make another PR fixing only that, as I think my fixes in dev already addressed #235 sufficiently.

**Comment by Gleethos** [comment]
I have not addressed #237 in my changes of this PR,
although I did make an adjustment in the third commit which simply makes sure that indents are only determined on a block by block basis, meaning that the indents of one block do not change the indents of another block.
So after my first two commits the following
problem occurred:
```groovy
    given :
def something = new Something()
    expect:
    something.isValid()
```
would lead to the following code strings:
(If we put all code lines into one list)
```groovy
[
    "def something = new Something ()",
    "    something.isValid()"
]
```
**I did not remove the condition which forbids the inclusion of `where` block code in my commits!**
However I tried disabling them and noticed how easy is was to enable it, because this did not break anything when I tested it on my test suites...

I could have done a better job here definately, these 4 commits should have been 1 clean commit.

**Comment by Gleethos** [comment]
I looked into your changes and tested them locally and it seems this is fully
fixed, the indents are even consistent on a block by block basis as I described in the previous comment!
I will close this pull request now.

**Pull request closed without merging**
